# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
# Generated callers pin both references to one reviewed immutable rockrel SHA.

name: Cherry-pick request

on:
  pull_request_target:
    types: [labeled, unlabeled, edited, synchronize, closed]

permissions:
  contents: read

jobs:
  process:
    uses: ROCm/rockrel/.github/workflows/cherry_pick.yml@ROCKREL_AUTOMATION_SHA
    with:
      source_pr: ${{ github.event.pull_request.html_url }}
      automation_ref: ROCKREL_AUTOMATION_SHA
      event_action: ${{ github.event.action }}
      event_label: ${{ github.event.label.name }}
      labels_json: ${{ toJSON(github.event.pull_request.labels.*.name) }}
    secrets:
      ROCM_CHERRYPICK_APP_CLIENT_ID: ${{ secrets.ROCM_CHERRYPICK_APP_CLIENT_ID }}
      ROCM_CHERRYPICK_APP_PRIVATE_KEY: ${{ secrets.ROCM_CHERRYPICK_APP_PRIVATE_KEY }}
