name: Multi-Arch Release

# Expected triggers:
#
# Release type | Trigger details
# ------------ | --------------------------------------------------------------
# dev          | "workflow_dispatch" for testing with any set of inputs
# nightly      | "schedule", or "workflow_dispatch" as needed (default inputs)
# prerelease   | "workflow_dispatch" for stable releases (explicit GPU family lists?)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type: "dev", "nightly", or "prerelease".'
        type: choice
        options:
          - dev
          - nightly
          - prerelease
        default: dev
      prerelease_version:
        description: "(Optional) Prerelease version number, e.g. '2' for 7.10.0rc2"
        type: string
        default: ""
      linux_amdgpu_families:
        description: 'Linux GPU families. "all" = all, "none" = skip Linux.'
        type: string
        default: "all"
      windows_amdgpu_families:
        description: 'Windows GPU families. "all" = all, "none" = skip Windows.'
        type: string
        default: "all"
      ref:
        description: "TheRock branch, tag, or SHA. Empty = default branch."
        type: string
        default: ""

  # Trigger on a schedule to build nightly releases.
  schedule:
    # Runs at 12:00 AM UTC, which is 5:00 PM PDT (UTC-7)
    - cron: '0 00 * * *'

permissions:
  contents: read

run-name: >-
  Multi-Arch Release (${{ inputs.release_type || 'nightly' }})
  | Linux: ${{ inputs.linux_amdgpu_families || 'all' }}
  | Windows: ${{ inputs.windows_amdgpu_families || 'all' }}

jobs:
  notify_quartz_start:
    if: ${{ vars.NOTIFY_QUARTZ_ENABLED == 'true' }}
    uses: ROCm/TheRock/.github/workflows/notify_quartz.yml@main
    with:
      run_phase: started
      reporting_workflow: multi_arch_release.yml
      workflow_inputs: ${{ toJSON(inputs) }}
      workflow_captured_outputs: ${{ toJSON(needs) }}
    secrets: inherit

  release:
    uses: ROCm/TheRock/.github/workflows/multi_arch_release.yml@main
    secrets: inherit
    with:
      release_type: ${{ inputs.release_type || 'nightly' }}
      prerelease_version: ${{ inputs.prerelease_version || '' }}
      linux_amdgpu_families: ${{ inputs.linux_amdgpu_families || 'all' }}
      windows_amdgpu_families: ${{ inputs.windows_amdgpu_families || 'all' }}
      run_full_pytorch_tests: ${{ github.event_name == 'schedule' }}
      repository: "ROCm/TheRock"
      ref: ${{ inputs.ref || '' }}
    permissions:
      contents: write
      actions: write
      id-token: write

  notify_quartz_completed:
    if: ${{ always() && vars.NOTIFY_QUARTZ_ENABLED == 'true' }}
    needs: [release]
    uses: ROCm/TheRock/.github/workflows/notify_quartz.yml@main
    with:
      run_phase: completed
      reporting_workflow: multi_arch_release.yml
      workflow_inputs: ${{ toJSON(inputs) }}
      workflow_captured_outputs: ${{ toJSON(needs) }}
    secrets: inherit
